package climat.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ParameterPresence extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ParameterPresence() {
    super(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988ab86fcbL, "ParameterPresence", "r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543930315");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_mandatory_0 = new EnumerationDescriptor.MemberDescriptor("mandatory", "!", 0x5db90e988ab86fcdL, "r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543930317");
  private final EnumerationDescriptor.MemberDescriptor myMember_optional_0 = new EnumerationDescriptor.MemberDescriptor("optional", "?", 0x5db90e988ab86fccL, "r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543930316");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988ab86fcbL, 0x5db90e988ab86fcdL, 0x5db90e988ab86fccL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_mandatory_0, myMember_optional_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_mandatory_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "mandatory":
        return myMember_mandatory_0;
      case "optional":
        return myMember_optional_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
