package climat.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptAnnotation = createDescriptorForAnnotation();
  /*package*/ final ConceptDescriptor myConceptAnnotationSection = createDescriptorForAnnotationSection();
  /*package*/ final ConceptDescriptor myConceptConstant = createDescriptorForConstant();
  /*package*/ final ConceptDescriptor myConceptCustomScriptAction = createDescriptorForCustomScriptAction();
  /*package*/ final ConceptDescriptor myConceptInterpolationTemplatePiece = createDescriptorForInterpolationTemplatePiece();
  /*package*/ final ConceptDescriptor myConceptJavaScriptAction = createDescriptorForJavaScriptAction();
  /*package*/ final ConceptDescriptor myConceptParameter = createDescriptorForParameter();
  /*package*/ final ConceptDescriptor myConceptReferenceable = createDescriptorForReferenceable();
  /*package*/ final ConceptDescriptor myConceptRootToolchain = createDescriptorForRootToolchain();
  /*package*/ final ConceptDescriptor myConceptShellAction = createDescriptorForShellAction();
  /*package*/ final ConceptDescriptor myConceptStringTemplatePiece = createDescriptorForStringTemplatePiece();
  /*package*/ final ConceptDescriptor myConceptTemplatePiece = createDescriptorForTemplatePiece();
  /*package*/ final ConceptDescriptor myConceptToolchain = createDescriptorForToolchain();
  /*package*/ final ConceptDescriptor myConceptToolchainBody = createDescriptorForToolchainBody();
  /*package*/ final ConceptDescriptor myConceptToolchainSignature = createDescriptorForToolchainSignature();
  /*package*/ final EnumerationDescriptor myEnumerationParameterPresence = new EnumerationDescriptor_ParameterPresence();
  /*package*/ final EnumerationDescriptor myEnumerationParameterType = new EnumerationDescriptor_ParameterType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptAnnotation, myConceptAnnotationSection, myConceptConstant, myConceptCustomScriptAction, myConceptInterpolationTemplatePiece, myConceptJavaScriptAction, myConceptParameter, myConceptReferenceable, myConceptRootToolchain, myConceptShellAction, myConceptStringTemplatePiece, myConceptTemplatePiece, myConceptToolchain, myConceptToolchainBody, myConceptToolchainSignature);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Annotation:
        return myConceptAnnotation;
      case LanguageConceptSwitch.AnnotationSection:
        return myConceptAnnotationSection;
      case LanguageConceptSwitch.Constant:
        return myConceptConstant;
      case LanguageConceptSwitch.CustomScriptAction:
        return myConceptCustomScriptAction;
      case LanguageConceptSwitch.InterpolationTemplatePiece:
        return myConceptInterpolationTemplatePiece;
      case LanguageConceptSwitch.JavaScriptAction:
        return myConceptJavaScriptAction;
      case LanguageConceptSwitch.Parameter:
        return myConceptParameter;
      case LanguageConceptSwitch.Referenceable:
        return myConceptReferenceable;
      case LanguageConceptSwitch.RootToolchain:
        return myConceptRootToolchain;
      case LanguageConceptSwitch.ShellAction:
        return myConceptShellAction;
      case LanguageConceptSwitch.StringTemplatePiece:
        return myConceptStringTemplatePiece;
      case LanguageConceptSwitch.TemplatePiece:
        return myConceptTemplatePiece;
      case LanguageConceptSwitch.Toolchain:
        return myConceptToolchain;
      case LanguageConceptSwitch.ToolchainBody:
        return myConceptToolchainBody;
      case LanguageConceptSwitch.ToolchainSignature:
        return myConceptToolchainSignature;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationParameterPresence, myEnumerationParameterType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Action", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6703L);
    b.class_(false, false, false);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/1673101796775454467");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Annotation", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab65dfe4dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856895053");
    b.version(3);
    b.property("content", 0x572def6ab65dfe50L).type(PrimitiveTypeId.STRING).origin("6281940296856895056").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotationSection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "AnnotationSection", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab66288ffL);
    b.class_(false, false, false);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296857192703");
    b.version(3);
    b.aggregate("annotations", 0x572def6ab6628900L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab65dfe4dL).optional(true).ordered(true).multiple(true).origin("6281940296857192704").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConstant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Constant", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab654f578L);
    b.class_(false, false, false);
    b.parent(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988abe43d1L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856302968");
    b.version(3);
    b.aggregate("pieces", 0x572def6ab655af03L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L).optional(true).ordered(true).multiple(true).origin("6281940296856350467").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCustomScriptAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "CustomScriptAction", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383ddf3596L);
    b.class_(false, false, false);
    // extends: climat.structure.Action
    b.super_(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6703L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/1673101796775507350");
    b.version(3);
    b.property("runtimePath", 0x17380d383ddf3ed5L).type(PrimitiveTypeId.STRING).origin("1673101796775509717").done();
    b.property("customScript", 0x17380d383ddf3ed6L).type(PrimitiveTypeId.STRING).origin("1673101796775509718").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInterpolationTemplatePiece() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "InterpolationTemplatePiece", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab36L);
    b.class_(false, false, false);
    b.parent(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856349494");
    b.version(3);
    b.associate("reference", 0x5db90e988abe43d8L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988abe43d1L).optional(false).origin("6753445164544312280").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJavaScriptAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "JavaScriptAction", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6706L);
    b.class_(false, false, false);
    // extends: climat.structure.Action
    b.super_(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6703L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/1673101796775454470");
    b.version(3);
    b.property("javascript", 0x17380d383ddf35acL).type(PrimitiveTypeId.STRING).origin("1673101796775507372").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Parameter", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988aaf5f1eL);
    b.class_(false, false, false);
    b.parent(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988abe43d1L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543336222");
    b.version(3);
    b.property("type", 0x5db90e988aaf5f20L).type(MetaIdFactory.dataTypeId(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988ab86fc5L)).origin("6753445164543336224").done();
    b.property("presence", 0x5db90e988ab12f71L).type(MetaIdFactory.dataTypeId(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988ab86fcbL)).origin("6753445164543455089").done();
    b.property("shortHand", 0x17380d383dc76824L).type(PrimitiveTypeId.STRING).origin("1673101796773947428").done();
    b.aggregate("defaultDataType", 0x5db90e988abc156cL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L).optional(true).ordered(true).multiple(true).origin("6753445164544169324").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReferenceable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Referenceable", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988abe43d1L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164544312273");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRootToolchain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "RootToolchain", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab654f56dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856302957");
    b.version(3);
    b.aggregate("annotationSection", 0x572def6ab66119f3L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab66288ffL).optional(true).ordered(true).multiple(false).origin("6281940296857098739").done();
    b.aggregate("body", 0x572def6ab66119cfL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab6628906L).optional(true).ordered(true).multiple(false).origin("6281940296857098703").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShellAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "ShellAction", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988aad407bL);
    b.class_(false, false, false);
    // extends: climat.structure.Action
    b.super_(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6703L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543197307");
    b.version(3);
    b.aggregate("pieces", 0x5db90e988aad407cL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L).optional(true).ordered(true).multiple(true).origin("6753445164543197308").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStringTemplatePiece() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "StringTemplatePiece", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab33L);
    b.class_(false, false, false);
    b.parent(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856349491");
    b.version(3);
    b.property("content", 0x572def6ab656a68cL).type(PrimitiveTypeId.STRING).origin("6281940296856413836").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTemplatePiece() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "TemplatePiece", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655ab32L);
    b.interface_();
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856349490");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToolchain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "Toolchain", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655c228L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296856355368");
    b.version(3);
    b.aggregate("annotationSection", 0x572def6ab66119b8L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab66288ffL).optional(true).ordered(true).multiple(false).origin("6281940296857098680").done();
    b.aggregate("signature", 0x5db90e988ab08ffeL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988aaff613L).optional(false).ordered(true).multiple(false).origin("6753445164543414270").done();
    b.aggregate("body", 0x572def6ab6628904L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab6628906L).optional(true).ordered(true).multiple(false).origin("6281940296857192708").done();
    b.alias("sub");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToolchainBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "ToolchainBody", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab6628906L);
    b.class_(false, false, false);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6281940296857192710");
    b.version(3);
    b.aggregate("constants", 0x572def6ab6628908L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab654f578L).optional(true).ordered(true).multiple(true).origin("6281940296857192712").done();
    b.aggregate("action", 0x5db90e988aad407eL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x17380d383dde6703L).optional(true).ordered(true).multiple(false).origin("6753445164543197310").done();
    b.aggregate("toolchains", 0x572def6ab662890aL).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x572def6ab655c228L).optional(true).ordered(true).multiple(true).origin("6281940296857192714").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToolchainSignature() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("climat", "ToolchainSignature", 0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988aaff613L);
    b.class_(false, false, false);
    b.origin("r:a703dee7-679c-4011-a20a-7f09be120d3f(climat.structure)/6753445164543374867");
    b.version(3);
    b.aggregate("parameters", 0x5db90e988aaff614L).target(0x73bee2cc69694dd7L, 0xabeb6acc8e6703a8L, 0x5db90e988aaf5f1eL).optional(true).ordered(true).multiple(true).origin("6753445164543374868").done();
    return b.create();
  }
}
