name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [ '14.14', '18.7' ]

    name: Build with Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Execute Gradle build
        run: ./gradlew build -x integrationTests:jsNodeTest
      - name: Install climat
        run: npm install -g build\dist\js\productionExecutable
      - name: Run integration tests
        run: ./gradlew integrationTests:jsNodeTest


  test-windows:
    strategy:
      matrix:
        node-version: [ '14.14', '18.7' ]

    name: Build with Node ${{ matrix.node-version }} on windows-latest
    runs-on: windows-latest
    steps:
      - run: echo "${HOME}\climat\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Execute Gradle build
        run: ./gradlew build -x integrationTests:jsNodeTest
      - name: Install climat
        run: npm install -g build\dist\js\productionExecutable
      - name: Run integration tests
        run: ./gradlew integrationTests:jsNodeTest
