name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [ '14.14', '18.7' ]

    name: Build with Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: action/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - run: ./gradlew build

  test-windows:
    strategy:
      matrix:
        node-version: [ '14.14', '18.7' ]

    name: Build with Node ${{ matrix.node-version }} on windows-latest
    runs-on: windows-latest
    steps:
      - run: echo "${HOME}\climat\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: action/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - run: .\gradlew.bat build
